version: "3.7"

services:
  ziti-controller:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    environment:
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME:-ziti-controller}
      - ZITI_CTRL_ADVERTISED_ADDRESS=${ZITI_CTRL_ADVERTISED_ADDRESS:-ziti-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_CTRL_EDGE_IP_OVERRIDE=${ZITI_CTRL_EDGE_IP_OVERRIDE:-127.0.0.1}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_ADVERTISED_PORT:-6262}
      - ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION=${ZITI_EDGE_IDENTITY_ENROLLMENT_DURATION}
      - ZITI_ROUTER_ENROLLMENT_DURATION=${ZITI_ROUTER_ENROLLMENT_DURATION}
      - ZITI_USER=${ZITI_USER:-admin}
    secrets:
      - ziti_admin_password
    networks:
      ziti:
        aliases:
          - ziti-edge-controller
    volumes:
      - ziti-fs:/persistent
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "export ZITI_PWD=$(cat /run/secrets/ziti_admin_password) && /var/openziti/scripts/run-controller.sh"
    deploy:
      placement:
        constraints: [node.role == worker]

  ziti-controller-init-container:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"
    networks:
      ziti:
    volumes:
      - ziti-fs:/persistent
      - ziti-enrollment:/enrollment
    entrypoint: ["/bin/bash"]
    command:
      - "-c"
      - "/var/openziti/scripts/run-with-ziti-cli.sh /var/openziti/scripts/access-control.sh && cp /persistent/*.jwt /enrollment/ 2>/dev/null || true"
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

  ziti-console:
    image: openziti/zac
    working_dir: /usr/src/app
    environment:
      - ZAC_SERVER_CERT_CHAIN=/persistent/pki/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}-intermediate/certs/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}-server.cert
      - ZAC_SERVER_KEY=/persistent/pki/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}-intermediate/keys/${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}-server.key
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_CTRL_NAME=${ZITI_CTRL_NAME:-ziti-edge-controller}
      - PORTTLS=8443
    volumes:
      - ziti-fs:/persistent
    networks:
      - ziti
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  ziti-edge-router:
    image: "${ZITI_IMAGE}:${ZITI_VERSION}"

    environment:
      - ZITI_CTRL_ADVERTISED_ADDRESS=${ZITI_CTRL_ADVERTISED_ADDRESS:-ziti-controller}
      - ZITI_CTRL_ADVERTISED_PORT=${ZITI_CTRL_ADVERTISED_PORT:-6262}
      - ZITI_CTRL_EDGE_ADVERTISED_ADDRESS=${ZITI_CTRL_EDGE_ADVERTISED_ADDRESS:-ziti-edge-controller}
      - ZITI_CTRL_EDGE_ADVERTISED_PORT=${ZITI_CTRL_EDGE_ADVERTISED_PORT:-1280}
      - ZITI_ROUTER_NAME=${ZITI_ROUTER_NAME:-ziti-edge-router}
      - ZITI_ROUTER_ADVERTISED_ADDRESS=${ZITI_ROUTER_ADVERTISED_ADDRESS:-ziti-edge-router}
      - ZITI_ROUTER_PORT=${ZITI_ROUTER_PORT:-3022}
      - ZITI_ROUTER_LISTENER_BIND_PORT=${ZITI_ROUTER_LISTENER_BIND_PORT:-10080}
      - ZITI_ROUTER_ROLES=public
    networks:
      - ziti
    volumes:
      - ziti-router-data:/persistent
      - ziti-enrollment:/enrollment:ro
    entrypoint: /bin/bash
    command:
      - "-c"
      - "cp /enrollment/*.jwt /persistent/ 2>/dev/null || true && /var/openziti/scripts/run-router.sh edge"
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == worker]

  web-test:
    image: openziti/hello-world

    networks:
      ziti:

networks:
  ziti:

volumes:
  ziti-fs:
  ziti-router-data:
  ziti-enrollment:

secrets:
  ziti_admin_password:
    file: ./secrets/ziti_admin_password
