- name: Gather file stats and checksums
  stat:
    path: "{{ item.file_path }}"
    checksum: md5
  loop: "{{ configs }}"
  register: file_stats

- name: Create dictionary of checksums
  set_fact:
    config_checksums: "{{ config_checksums | default({}) | combine({ item.name: file_stats.results[idx].stat.checksum }) }}"
  loop: "{{ configs }}"
  loop_control:
    index_var: idx

- name: Create new configs if value has changed
  docker_config:
    name: "{{ item.name }}_{{ config_checksums[item.name] }}"
    data_src: "{{ item.file_path }}"
    state: present
    labels:
      managed_by: "rotate_docker_configs"
      name: "{{ item.name }}"
  loop: "{{ configs }}"

- name: Replace config names in Docker Compose file
  replace:
    path: "{{ docker_compose_path }}"
    regexp: "{{ item.name }}(_[a-f0-9]{32})?"
    replace: "{{ item.name }}_{{ config_checksums[item.name] }}"
  loop: "{{ configs }}"
