- name: This speeds up playbook in PRs
  hosts: localhost
  gather_facts: false
  vars:
    roles_folder: "{{ playbook_dir }}/roles"
    default_branch: main

  tasks:
  - name: Register current branch
    ansible.builtin.command: git rev-parse --abbrev-ref HEAD
    register: branch
    tags:
    - skip_ansible_lint

  - name: Debug branch output
    debug:
      msg: "{{ branch.stdout }}"

  - name: Register the git diff
    ansible.builtin.command: git diff --name-only origin/{{ default_branch }}..origin/{{ branch.stdout }} .
    when: branch.stdout != default_branch
    register: diff
    tags:
    - skip_ansible_lint

  - name: Debug diff output
    debug:
      msg: "{{ diff.stdout_lines }}"
    when: branch.stdout != default_branch

  - name: Extract folders from the diff
    when: branch.stdout != default_branch
    set_fact:
      changed_folders: "{{ diff.stdout_lines 
        | map('regex_replace', '^(.*/).*$' , '\\1') 
        | unique }}"

  - name: Filter folders within the roles directory
    when: branch.stdout != default_branch
    set_fact:
    utils_affected_roles_roles_with_changes: "{{ changed_folders
      | select('match', '^' + roles_folder + '/')
      | map('regex_replace', '^' + roles_folder + '/([^/]+)/.*$', '\\1')
      | unique }}"

  - name: List all existing roles
    find:
      paths: "{{ roles_folder }}"
      recurse: false
      file_type: directory
    register: found_directories
    when: branch.stdout == default_branch

  - name: Set all roles to run if on default branch
    set_fact:
      utils_affected_roles_roles_with_changes: "{{ found_directories.files 
        | map(attribute='path') 
        | map('basename') 
        | list }}"
    when: branch.stdout == default_branch

  - name: Debug utils_affected_roles_roles_with_changes output
    debug:
      msg: "{{ utils_affected_roles_roles_with_changes }}"

- name: Conditionally run roles based on changes
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Include role1 if it has changes
    include_role:
      name: role1
    when: "'role1' in utils_affected_roles_roles_with_changes"

  - name: Include role2 if it has changes
    include_role:
      name: role2
    when: "'role2' in utils_affected_roles_roles_with_changes"

  - name: Include role3 if it has changes
    include_role:
      name: role3
    when: "'role3' in utils_affected_roles_roles_with_changes"