terraform_digitalocean_backend_config: "{{ role_path }}/assets/backend.tf"

# Ansible Inventory Configuration
terraform_digitalocean_inventory_path: "{{ playbook_dir }}/inventory"
terraform_digitalocean_inventory_prefix: do-swarm
terraform_digitalocean_inventory_user: root

# Destroy flag
terraform_digitalocean_destroy: false
