---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: infra-addons
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/xnok/manifests/kubernetes/infra-addons
  ref:
    tag: latest
  provider: generic
