tasks:
  - name: Setup Environment
    init: |
      ./bin/bash/setup.sh pre-commit ansible 1password-cli boilerplate hugo
    command: |
      cd website && hugo server -D -F --baseURL $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0
