apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - namespace.yaml
  - keycloak.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: default-keycloak-values
    namespace: flux-system
    files:
      - values.yaml=default-keycloak.values.yaml
