apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - namespace.yaml
  - controller.yaml
  - ziti-host.yaml
  - router-enrollment-job.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: ziti-router-enroll-script
    namespace: openziti
    files:
      - enroll-router.sh
  - name: default-ziti-controller-values
    namespace: flux-system
    files:
      - values.yaml=default-ziti-controller.values.yaml
  - name: default-ziti-router-values
    namespace: flux-system
    files:
      - values.yaml=default-ziti-router.values.yaml
