apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
  - cert-manager.yaml
  - trust-manager.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
  - name: default-cert-manager-values
    namespace: flux-system
    files:
      - values.yaml=default-cert-manager.values.yaml
  - name: default-trust-manager-values
    namespace: flux-system
    files:
      - values.yaml=default-trust-manager.values.yaml
