apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  chart:
    spec:
      chart: trust-manager
      version: "v0.22.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: default-trust-manager-values
    - kind: ConfigMap
      name: ${CLUSTER_NAME}-trust-manager-values
      optional: true
