apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    reconcile.fluxcd.io/watch: Enabled

configMapGenerator:
  - name: k3s-cert-manager-values
    namespace: flux-system
    files:
      - values.yaml=cert-manager.values.yaml
  - name: k3s-trust-manager-values
    namespace: flux-system
    files:
      - values.yaml=trust-manager.values.yaml
  - name: k3s-ziti-controller-values
    namespace: flux-system
    files:
      - values.yaml=ziti-controller.values.yaml
  - name: k3s-ziti-router-values
    namespace: flux-system
    files:
      - values.yaml=ziti-router.values.yaml
