- name: List all Docker secrets managed by this role
  command: docker secret ls --filter label=managed_by=rotate_docker_secrets --format "{{ '{{.Name}}' }}"
  register: existing_secrets

- name: Identify secrets to keep
  set_fact:
    secrets_to_keep: "{{ secrets_to_keep | default([]) + [item.name + '_' + secret_checksums[item.name]] }}"
  loop: "{{ secrets }}"

- name: Remove dangling secrets
  docker_secret:
    name: "{{ item }}"
    state: absent
  when: item not in secrets_to_keep
  loop: "{{ existing_secrets.stdout_lines }}"
  ignore_errors: true
