checksum_directory: /var/data/ansible
docker_compose_path: "{{ undef(hint='You must specify docker-compose file to update') }}"
docker_stack_name: "{{ undef(hint='You must specify stack to update') }}"

