apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: kind-cert-manager-values
    namespace: flux-system
    files:
      - values.yaml=cert-manager.values.yaml
  - name: kind-trust-manager-values
    namespace: flux-system
    files:
      - values.yaml=trust-manager.values.yaml
  - name: kind-ziti-controller-values
    namespace: flux-system
    files:
      - values.yaml=ziti-controller.values.yaml
  - name: kind-ziti-router-values
    namespace: flux-system
    files:
      - values.yaml=ziti-router.values.yaml
