# BASE
- name: This is the base requirement for all nodes
  hosts: all
  become: true

  roles:
  - role: docker
    when: "'docker' in hostvars['localhost']['utils_affected_roles_roles_with_changes']"

# SWARM
- name: This setup the Docker Swarm Manager
  hosts: managers
  gather_facts: true
  become: true

  roles:
  # NOTE: One node requires python and extra tools to setup the swarm, I call it the controller.
  # I case we have an issue all master are setup as potential controller
  # this role is for the host running ansible to manage the swarm
  - role: docker_swarm_controller
  # this role is for creating the swarm and adding host as manager
  - role: docker_swarm_manager

- name: This setup nodes to join the Swarm
  hosts: nodes

  roles:
  - role: docker_swarm_node # this role is for host to join the swarm

# APPS
- name: This install Caddy and Portainer in the Swarm
  hosts: managers[0] # Only one manager need to be hit
  become: true

  roles:
  - role: docker_swarm_app_caddy
  - role: docker_swarm_app_portainer
    docker_swarm_app_portainer_caddy: true
