- name: This is the base requirement for all nodes
  hosts: docker_swarm_managers:docker_swarm_nodes
  become: true

  roles:
  - xnok.infra_bootstrap_tools.docker

- name: This setup the Docker Swarm Manager
  hosts: docker_swarm_managers
  become: true

  roles:
  - xnok.infra_bootstrap_tools.docker_swarm_manager # this role is for creating the swarm and adding host as manager

- name: This setup nodes to join the Swarm
  hosts: docker_swarm_nodes

  roles:
  - xnok.infra_bootstrap_tools.docker_swarm_node # this role is for host to join the swarm
