version: "3.9"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["caddy", "docker-proxy"]
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8443:8443/udp"
    networks:
      - gitpod
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    secrets:
      - caddy_github_auth

  whoami0:
    image: containous/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: whoami0.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

volumes:
  caddy_data:
  caddy_config:

networks:
  gitpod:
    driver: bridge
    # default MTU size in docker-compose is 1500
    driver_opts:
      com.docker.network.driver.mtu: 1440

secrets:
  caddy_github_auth:
    file: ./caddy_github_auth.env
