name: 'PR Lock'
description: 'Ensure that only one PR can deploy at a time using a lock file mechanism.'
runs:
  using: 'composite'
  steps:
    - name: Checkout lock branch
      shell: bash
      run: |
        git fetch origin lock-branch || echo "No remote lock-branch found, creating a new one."
        git checkout lock-branch || git checkout --orphan lock-branch

    - name: Check for lock file
      id: check-lock
      shell: bash
      run: |
        if [ -f ".deploy-lock" ]; then
          echo "Another deployment is in progress. Exiting..."
          exit 1
        fi

    - name: Create lock file
      shell: bash
      id: create-lock
      run: |
        echo "Creating lock file..."
        echo "${{ github.event.pull_request.number }}" > .deploy-lock
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .deploy-lock
        git commit -m "Lock deployment for PR #${{ github.event.pull_request.number }}"
        git push origin lock-branch
