galaxy_info:
  author: xNok
  description: Installs and configures Docker.
  license: MIT
  min_ansible_version: '2.9' # Or your desired minimum version
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
    - containerization
    # Add other relevant tags

dependencies: [] # List any dependencies here
