galaxy_info:
  author: xNok
  description: Initializes a Docker Swarm cluster and configures it as a controller.
  license: MIT
  min_ansible_version: '2.9' # Or your desired minimum version
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
    - swarm
    - controller
    # Add other relevant tags

dependencies: [] # List any dependencies here
