#################################################
# OR INFRA Role: utils-ssh-add
# ref: https://stackoverflow.com/questions/76194954/playbook-to-add-ssh-key-having-passphrase-and-reuse-ssh-auth-sock-ssh-agent-pid
#################################################
---

- name: Ensure destination directory for SSH key exists
  when: private_key_openssh is defined
  ansible.builtin.file:
    path: "{{ utils_ssh_add_ansible_ssh_private_key_file | dirname }}"
    state: directory
    mode: '0700'

- name: Add private key SSH Agent
  when: private_key_openssh is defined
  ansible.builtin.copy:
    dest: "{{ utils_ssh_add_ansible_ssh_private_key_file }}"
    content: "{{ private_key_openssh }}"
    mode: '0600'

- name: Start ssh-agent and Retrieve the SSH_AUTH_SOCK and SSH_AGENT_PID environment variables
  shell: |
      eval $(ssh-agent -s) > /dev/null
      echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'
  register: utils_ssh_add_env_vars_stdout
  changed_when: env_vars_stdout.rc != 0

- name: Save to env_vars
  set_fact:
    utils_ssh_add_ssh_agent_pid: "{{ utils_ssh_add_env_vars_stdout.stdout | from_json | json_query('SSH_AGENT_PID') }}"
    utils_ssh_add_ssh_auth_sock: "{{ utils_ssh_add_env_vars_stdout.stdout | from_json | json_query('SSH_AUTH_SOCK') }}"

- name: Add to ssh-agent {{ utils_ssh_add_ansible_ssh_private_key_file }}
  environment:
    SSH_AGENT_PID: "{{ utils_ssh_add_ssh_agent_pid }}"
    SSH_AUTH_SOCK: "{{ utils_ssh_add_ssh_auth_sock }}"
  command: ssh-add {{ utils_ssh_add_ansible_ssh_private_key_file }}
  register: utils_ssh_add_ssh_add
  changed_when: utils_ssh_add_ssh_add.rc != 0
