version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    volumes:
      - n8n_data:/home/node/.n8n
    # Docker Stack Config
    networks:
      - caddy_caddy
    deploy:
      labels:
        caddy: ${SUBDOMAIN}.${DOMAIN_NAME}
        # Routes for webhook do not need oauth
        caddy.route_0: /rest/oauth2-credential/callback
        caddy.route_0.reverse_proxy: "{{ upstreams 5678 }}"
        # Default route
        caddy.route_1.reverse_proxy: "{{ upstreams 5678 }}"
        caddy.route_1.authorize: with admins_policy

volumes:
  n8n_data:
    external: true

networks:
  caddy_caddy:
    external: true