- name: This is a hello-world example
  hosts: localhost
  gather_facts: true
  become: true

  environment:
    DIGITALOCEAN_ACCESS_TOKEN: "{{
      lookup('community.general.onepassword', 'DIGITALOCEAN_ACCESS_TOKEN',
      vault='infra-bootstrap-tools', field='credential')
      }}"

  roles:
  - terraform-digitalocean
