version: '3.8'

services:
  mcphub:
    image: samanhappy/mcphub
    restart: unless-stopped
    networks:
      - n8n_n8n
      - caddy_caddy
    volumes:
      - mcphub_data:/app/data
      - mcphub_logs:/app/logs
      - mcphub_config:/app/config
    environment:
      - NODE_ENV=production
      - MCP_SETTINGS_FILE=/app/config/mcp_settings.json
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - DATABASE_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - mcphub_jwt_secret
      - mcphub_db_password
    deploy:
      placement:
        constraints:
          - node.role != manager
      labels:
        caddy: ${SUBDOMAIN}.${DOMAIN_NAME}
        caddy.reverse_proxy: "{{ upstreams 3000 }}"
        caddy.authorize: with admins_policy

volumes:
  mcphub_logs:
  mcphub_data:
  mcphub_config:

secrets:
  jwt_secret:
    external: true
  db_password:
    external: true

networks:
  # Define the external network created by your n8n stack
  n8n_n8n:
    external: true
  # Define the external network created by your Caddy stack to expose the dashboard
  caddy_caddy:
    external: true
