version: '3.8'

services:
  mcphub:
    image: samanhappy/mcphub
    restart: unless-stopped
    networks:
      - n8n_n8n
      - caddy_caddy
    volumes:
      - mcphub_data:/app/data
      - mcphub_logs:/app/logs
      - mcphub_config:/app/config
    deploy:
      placement:
        constraints:
          - node.role != manager
      labels:
        caddy: ${SUBDOMAIN}.${DOMAIN_NAME}
        caddy.reverse_proxy: "{{ upstreams 3000 }}"
        caddy.authorize: with admins_policy

volumes:
  mcphub_logs:
  mcphub_data:
  mcphub_config:

networks:
  # Define the external network created by your n8n stack
  n8n_n8n:
    external: true
  # Define the external network created by your caddy stack to expose dashboard
  caddy_caddy:
    external: true
