version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.123.11
    restart: always
    environment:
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
    volumes:
      - n8n_data:/home/node/.n8n
    # Docker Stack Config
    networks:
      - caddy_caddy
      - n8n
    deploy:
      placement:
        constraints:
          - node.role != manager
      labels:
        caddy: ${SUBDOMAIN}.${DOMAIN_NAME}
        caddy.0_route: /webhook/*
        caddy.0_route.reverse_proxy: "{{ upstreams 5678 }}"
        # Default route
        caddy.1_route: /rest/oauth2-credential/callback
        caddy.1_route.reverse_proxy: "{{ upstreams 5678 }}"
        caddy.2_route: "*"
        caddy.2_route.reverse_proxy: "{{ upstreams 5678 }}"
        caddy.2_route.authorize: with admins_policy

volumes:
  n8n_data:
    external: true

networks:
  caddy_caddy:
    external: true
  n8n:
    attachable: true
