#################################################
# OR INFRA Role: Docker Swarm Controller
# Machines running ansible need some special python package
# Source:
#    https://github.com/arillso/ansible.traefik
#    https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik/
#################################################

###
# GENERAL Setup
###
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: ['pipx', 'python3-setuptools', 'python3-jsondiff', 'python3-passlib', 'python3-docker']
