version: "3.9"

services:
  caddy:
    image: ghcr.io/xnok/infra-bootstrap-tools-caddy:main
    command:
      - "caddy"
      - "docker-proxy"
      - "--caddyfile-path"
      - "/etc/caddy/Caddyfile"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ caddy_dir }}/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    environment:
      GITHUB_CLIENT_ID_FILE: ${GITHUB_CLIENT_ID_FILE}
      GITHUB_CLIENT_SECRET_FILE: ${GITHUB_CLIENT_SECRET_FILE}
      JWT_SHARED_KEY_FILE: ${JWT_SHARED_KEY_FILE}

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: whoami.{{domain}}
        # this include escape for ansible
        caddy.reverse_proxy: "{{ '{{' }}upstreams 80{{ '}}' }}"
        caddy.authorize: with admins_policy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    attachable: true

