name: "Test Flux Bootstrap"

on:
  pull_request:
    paths:
      - "kubernetes/**"
      - "bin/tests/flux-d2/test.sh"
      - "bin/k8s/setup-kind-local-registry.sh"
      - "bin/kind/config/**"
      - ".github/workflows/flux-test.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: nix develop .#flux --command bash -eo pipefail {0}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          cluster_name: kind
          registry: true


      - name: Run Test Script
        env:
          CLUSTER_NAME: kind
          FLEET_NAME: kind
          SOURCE_URL: ${{ github.event.repository.html_url }}
          REVISION: ${{ github.sha }}
        run: ./bin/ci/run-flux-test.sh
